name: CI

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies for mommy
        run: |
          git clone --depth=1 https://github.com/shellspec/shellspec.git
          sudo make -C shellspec install
      - name: Checkout mommy
        uses: actions/checkout@v3
        with:
          repository: FWDekker/mommy
          path: mommy
          ref: dev

      - name: Install Homebrew
        run: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Checkout homebrew-mommy
        uses: actions/checkout@v3
        with:
          path: homebrew-mommy
      - name: Test Homebrew package
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          echo "::group::Install"
          brew tap local/mommy "$(pwd)/homebrew-mommy"
          brew install mommy --HEAD
          echo "::endgroup::"

          echo "::group::Test"
          MOMMY_EXEC=mommy make -C mommy test
          echo "::endgroup::"

          echo "::group::Uninstall"
          brew uninstall mommy
          brew untap local/mommy
          echo "::endgroup::"
